// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Messages.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Google.Protobuf.Message {

  /// <summary>Holder for reflection information generated from Messages.proto</summary>
  public static partial class MessagesReflection {

    #region Descriptor
    /// <summary>File descriptor for Messages.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MessagesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5NZXNzYWdlcy5wcm90bxIHTWVzc2FnZRofZ29vZ2xlL3Byb3RvYnVmL3Rp",
            "bWVzdGFtcC5wcm90byKzAQoJR2FtZUFjdG9yEgwKBGd1aWQYASABKAkSDAoE",
            "bmFtZRgCIAEoCRIMCgR0ZWFtGAMgASgJEhAKCG1hcF9jb2RlGAQgASgJEh4K",
            "FmFlc3RoZXRpY19zY2FsZV9mYWN0b3IYBSABKAISHAoUaWRsZV9zcHJpdGVf",
            "ZmlsZW5hbWUYBiABKAkSGwoTbGl2ZXNfaWNvbl9maWxlbmFtZRgHIAEoCRIP",
            "CgdzY3JpcHRzGAggAygJIvMBCg5HYW1lQ29uZmlnRGF0YRIMCgRuYW1lGAEg",
            "ASgJEiUKHXRpdGxlX3NjcmVlbl9iYWNrZ3JvdW5kX2ltYWdlGAIgASgJEh8K",
            "F3RpdGxlX3NjcmVlbl9sb2dvX2ltYWdlGAMgASgJEhoKEmluaXRpYWxfc2Nl",
            "bmVfZmlsZRgEIAEoCRIWCg5nYW1lb3Zlcl9pbWFnZRgFIAEoCRIhChlnYW1l",
            "b3Zlcl9iYWNrZ3JvdW5kX2ltYWdlGAYgASgJEh4KFmluaXRpYWxfY29udGlu",
            "dWVfY291bnQYByABKAUSFAoMY3Vyc29yX2ltYWdlGAggASgJIhkKCE1vZEZp",
            "bGVzEg0KBWZpbGVzGAEgAygJIgUKA01hcCIfCgxTaW1wbGVTdHJpbmcSDwoH",
            "bWVzc2FnZRgBIAEoCSKwAQoRQWN0b3JDb21iYXRDb25maWcSEwoLYXR0YWNr",
            "UmFuZ2UYASABKAUSFAoMYXR0YWNrRGFtYWdlGAIgASgFEhcKD2NyaXRpY2Fs",
            "SGl0UmF0ZRgDIAEoAhIUCgxhdHRhY2tXaW5kdXAYBCABKAISFgoOYXR0YWNr",
            "UmVjb3ZlcnkYBSABKAISFgoOYXR0YWNrQ29vbGRvd24YBiABKAISEQoJc3Rh",
            "dGVOYW1lGAcgASgJQhqqAhdHb29nbGUuUHJvdG9idWYuTWVzc2FnZWIGcHJv",
            "dG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Protobuf.Message.GameActor), global::Google.Protobuf.Message.GameActor.Parser, new[]{ "Guid", "Name", "Team", "MapCode", "AestheticScaleFactor", "IdleSpriteFilename", "LivesIconFilename", "Scripts" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Protobuf.Message.GameConfigData), global::Google.Protobuf.Message.GameConfigData.Parser, new[]{ "Name", "TitleScreenBackgroundImage", "TitleScreenLogoImage", "InitialSceneFile", "GameoverImage", "GameoverBackgroundImage", "InitialContinueCount", "CursorImage" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Protobuf.Message.ModFiles), global::Google.Protobuf.Message.ModFiles.Parser, new[]{ "Files" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Protobuf.Message.Map), global::Google.Protobuf.Message.Map.Parser, null, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Protobuf.Message.SimpleString), global::Google.Protobuf.Message.SimpleString.Parser, new[]{ "Message" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Protobuf.Message.ActorCombatConfig), global::Google.Protobuf.Message.ActorCombatConfig.Parser, new[]{ "AttackRange", "AttackDamage", "CriticalHitRate", "AttackWindup", "AttackRecovery", "AttackCooldown", "StateName" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class GameActor : pb::IMessage<GameActor>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GameActor> _parser = new pb::MessageParser<GameActor>(() => new GameActor());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GameActor> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Protobuf.Message.MessagesReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GameActor() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GameActor(GameActor other) : this() {
      guid_ = other.guid_;
      name_ = other.name_;
      team_ = other.team_;
      mapCode_ = other.mapCode_;
      aestheticScaleFactor_ = other.aestheticScaleFactor_;
      idleSpriteFilename_ = other.idleSpriteFilename_;
      livesIconFilename_ = other.livesIconFilename_;
      scripts_ = other.scripts_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GameActor Clone() {
      return new GameActor(this);
    }

    /// <summary>Field number for the "guid" field.</summary>
    public const int GuidFieldNumber = 1;
    private string guid_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Guid {
      get { return guid_; }
      set {
        guid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 2;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "team" field.</summary>
    public const int TeamFieldNumber = 3;
    private string team_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Team {
      get { return team_; }
      set {
        team_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "map_code" field.</summary>
    public const int MapCodeFieldNumber = 4;
    private string mapCode_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string MapCode {
      get { return mapCode_; }
      set {
        mapCode_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "aesthetic_scale_factor" field.</summary>
    public const int AestheticScaleFactorFieldNumber = 5;
    private float aestheticScaleFactor_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float AestheticScaleFactor {
      get { return aestheticScaleFactor_; }
      set {
        aestheticScaleFactor_ = value;
      }
    }

    /// <summary>Field number for the "idle_sprite_filename" field.</summary>
    public const int IdleSpriteFilenameFieldNumber = 6;
    private string idleSpriteFilename_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string IdleSpriteFilename {
      get { return idleSpriteFilename_; }
      set {
        idleSpriteFilename_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "lives_icon_filename" field.</summary>
    public const int LivesIconFilenameFieldNumber = 7;
    private string livesIconFilename_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string LivesIconFilename {
      get { return livesIconFilename_; }
      set {
        livesIconFilename_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "scripts" field.</summary>
    public const int ScriptsFieldNumber = 8;
    private static readonly pb::FieldCodec<string> _repeated_scripts_codec
        = pb::FieldCodec.ForString(66);
    private readonly pbc::RepeatedField<string> scripts_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> Scripts {
      get { return scripts_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GameActor);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GameActor other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Guid != other.Guid) return false;
      if (Name != other.Name) return false;
      if (Team != other.Team) return false;
      if (MapCode != other.MapCode) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(AestheticScaleFactor, other.AestheticScaleFactor)) return false;
      if (IdleSpriteFilename != other.IdleSpriteFilename) return false;
      if (LivesIconFilename != other.LivesIconFilename) return false;
      if(!scripts_.Equals(other.scripts_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Guid.Length != 0) hash ^= Guid.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Team.Length != 0) hash ^= Team.GetHashCode();
      if (MapCode.Length != 0) hash ^= MapCode.GetHashCode();
      if (AestheticScaleFactor != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(AestheticScaleFactor);
      if (IdleSpriteFilename.Length != 0) hash ^= IdleSpriteFilename.GetHashCode();
      if (LivesIconFilename.Length != 0) hash ^= LivesIconFilename.GetHashCode();
      hash ^= scripts_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Guid.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Guid);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (Team.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Team);
      }
      if (MapCode.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(MapCode);
      }
      if (AestheticScaleFactor != 0F) {
        output.WriteRawTag(45);
        output.WriteFloat(AestheticScaleFactor);
      }
      if (IdleSpriteFilename.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(IdleSpriteFilename);
      }
      if (LivesIconFilename.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(LivesIconFilename);
      }
      scripts_.WriteTo(output, _repeated_scripts_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Guid.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Guid);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (Team.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Team);
      }
      if (MapCode.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(MapCode);
      }
      if (AestheticScaleFactor != 0F) {
        output.WriteRawTag(45);
        output.WriteFloat(AestheticScaleFactor);
      }
      if (IdleSpriteFilename.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(IdleSpriteFilename);
      }
      if (LivesIconFilename.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(LivesIconFilename);
      }
      scripts_.WriteTo(ref output, _repeated_scripts_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Guid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Guid);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Team.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Team);
      }
      if (MapCode.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MapCode);
      }
      if (AestheticScaleFactor != 0F) {
        size += 1 + 4;
      }
      if (IdleSpriteFilename.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(IdleSpriteFilename);
      }
      if (LivesIconFilename.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(LivesIconFilename);
      }
      size += scripts_.CalculateSize(_repeated_scripts_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GameActor other) {
      if (other == null) {
        return;
      }
      if (other.Guid.Length != 0) {
        Guid = other.Guid;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Team.Length != 0) {
        Team = other.Team;
      }
      if (other.MapCode.Length != 0) {
        MapCode = other.MapCode;
      }
      if (other.AestheticScaleFactor != 0F) {
        AestheticScaleFactor = other.AestheticScaleFactor;
      }
      if (other.IdleSpriteFilename.Length != 0) {
        IdleSpriteFilename = other.IdleSpriteFilename;
      }
      if (other.LivesIconFilename.Length != 0) {
        LivesIconFilename = other.LivesIconFilename;
      }
      scripts_.Add(other.scripts_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Guid = input.ReadString();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 26: {
            Team = input.ReadString();
            break;
          }
          case 34: {
            MapCode = input.ReadString();
            break;
          }
          case 45: {
            AestheticScaleFactor = input.ReadFloat();
            break;
          }
          case 50: {
            IdleSpriteFilename = input.ReadString();
            break;
          }
          case 58: {
            LivesIconFilename = input.ReadString();
            break;
          }
          case 66: {
            scripts_.AddEntriesFrom(input, _repeated_scripts_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Guid = input.ReadString();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 26: {
            Team = input.ReadString();
            break;
          }
          case 34: {
            MapCode = input.ReadString();
            break;
          }
          case 45: {
            AestheticScaleFactor = input.ReadFloat();
            break;
          }
          case 50: {
            IdleSpriteFilename = input.ReadString();
            break;
          }
          case 58: {
            LivesIconFilename = input.ReadString();
            break;
          }
          case 66: {
            scripts_.AddEntriesFrom(ref input, _repeated_scripts_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class GameConfigData : pb::IMessage<GameConfigData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GameConfigData> _parser = new pb::MessageParser<GameConfigData>(() => new GameConfigData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GameConfigData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Protobuf.Message.MessagesReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GameConfigData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GameConfigData(GameConfigData other) : this() {
      name_ = other.name_;
      titleScreenBackgroundImage_ = other.titleScreenBackgroundImage_;
      titleScreenLogoImage_ = other.titleScreenLogoImage_;
      initialSceneFile_ = other.initialSceneFile_;
      gameoverImage_ = other.gameoverImage_;
      gameoverBackgroundImage_ = other.gameoverBackgroundImage_;
      initialContinueCount_ = other.initialContinueCount_;
      cursorImage_ = other.cursorImage_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GameConfigData Clone() {
      return new GameConfigData(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "title_screen_background_image" field.</summary>
    public const int TitleScreenBackgroundImageFieldNumber = 2;
    private string titleScreenBackgroundImage_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string TitleScreenBackgroundImage {
      get { return titleScreenBackgroundImage_; }
      set {
        titleScreenBackgroundImage_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "title_screen_logo_image" field.</summary>
    public const int TitleScreenLogoImageFieldNumber = 3;
    private string titleScreenLogoImage_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string TitleScreenLogoImage {
      get { return titleScreenLogoImage_; }
      set {
        titleScreenLogoImage_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "initial_scene_file" field.</summary>
    public const int InitialSceneFileFieldNumber = 4;
    private string initialSceneFile_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string InitialSceneFile {
      get { return initialSceneFile_; }
      set {
        initialSceneFile_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "gameover_image" field.</summary>
    public const int GameoverImageFieldNumber = 5;
    private string gameoverImage_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string GameoverImage {
      get { return gameoverImage_; }
      set {
        gameoverImage_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "gameover_background_image" field.</summary>
    public const int GameoverBackgroundImageFieldNumber = 6;
    private string gameoverBackgroundImage_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string GameoverBackgroundImage {
      get { return gameoverBackgroundImage_; }
      set {
        gameoverBackgroundImage_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "initial_continue_count" field.</summary>
    public const int InitialContinueCountFieldNumber = 7;
    private int initialContinueCount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int InitialContinueCount {
      get { return initialContinueCount_; }
      set {
        initialContinueCount_ = value;
      }
    }

    /// <summary>Field number for the "cursor_image" field.</summary>
    public const int CursorImageFieldNumber = 8;
    private string cursorImage_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string CursorImage {
      get { return cursorImage_; }
      set {
        cursorImage_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GameConfigData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GameConfigData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (TitleScreenBackgroundImage != other.TitleScreenBackgroundImage) return false;
      if (TitleScreenLogoImage != other.TitleScreenLogoImage) return false;
      if (InitialSceneFile != other.InitialSceneFile) return false;
      if (GameoverImage != other.GameoverImage) return false;
      if (GameoverBackgroundImage != other.GameoverBackgroundImage) return false;
      if (InitialContinueCount != other.InitialContinueCount) return false;
      if (CursorImage != other.CursorImage) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (TitleScreenBackgroundImage.Length != 0) hash ^= TitleScreenBackgroundImage.GetHashCode();
      if (TitleScreenLogoImage.Length != 0) hash ^= TitleScreenLogoImage.GetHashCode();
      if (InitialSceneFile.Length != 0) hash ^= InitialSceneFile.GetHashCode();
      if (GameoverImage.Length != 0) hash ^= GameoverImage.GetHashCode();
      if (GameoverBackgroundImage.Length != 0) hash ^= GameoverBackgroundImage.GetHashCode();
      if (InitialContinueCount != 0) hash ^= InitialContinueCount.GetHashCode();
      if (CursorImage.Length != 0) hash ^= CursorImage.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (TitleScreenBackgroundImage.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(TitleScreenBackgroundImage);
      }
      if (TitleScreenLogoImage.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(TitleScreenLogoImage);
      }
      if (InitialSceneFile.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(InitialSceneFile);
      }
      if (GameoverImage.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(GameoverImage);
      }
      if (GameoverBackgroundImage.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(GameoverBackgroundImage);
      }
      if (InitialContinueCount != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(InitialContinueCount);
      }
      if (CursorImage.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(CursorImage);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (TitleScreenBackgroundImage.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(TitleScreenBackgroundImage);
      }
      if (TitleScreenLogoImage.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(TitleScreenLogoImage);
      }
      if (InitialSceneFile.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(InitialSceneFile);
      }
      if (GameoverImage.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(GameoverImage);
      }
      if (GameoverBackgroundImage.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(GameoverBackgroundImage);
      }
      if (InitialContinueCount != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(InitialContinueCount);
      }
      if (CursorImage.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(CursorImage);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (TitleScreenBackgroundImage.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TitleScreenBackgroundImage);
      }
      if (TitleScreenLogoImage.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TitleScreenLogoImage);
      }
      if (InitialSceneFile.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(InitialSceneFile);
      }
      if (GameoverImage.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(GameoverImage);
      }
      if (GameoverBackgroundImage.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(GameoverBackgroundImage);
      }
      if (InitialContinueCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(InitialContinueCount);
      }
      if (CursorImage.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CursorImage);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GameConfigData other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.TitleScreenBackgroundImage.Length != 0) {
        TitleScreenBackgroundImage = other.TitleScreenBackgroundImage;
      }
      if (other.TitleScreenLogoImage.Length != 0) {
        TitleScreenLogoImage = other.TitleScreenLogoImage;
      }
      if (other.InitialSceneFile.Length != 0) {
        InitialSceneFile = other.InitialSceneFile;
      }
      if (other.GameoverImage.Length != 0) {
        GameoverImage = other.GameoverImage;
      }
      if (other.GameoverBackgroundImage.Length != 0) {
        GameoverBackgroundImage = other.GameoverBackgroundImage;
      }
      if (other.InitialContinueCount != 0) {
        InitialContinueCount = other.InitialContinueCount;
      }
      if (other.CursorImage.Length != 0) {
        CursorImage = other.CursorImage;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            TitleScreenBackgroundImage = input.ReadString();
            break;
          }
          case 26: {
            TitleScreenLogoImage = input.ReadString();
            break;
          }
          case 34: {
            InitialSceneFile = input.ReadString();
            break;
          }
          case 42: {
            GameoverImage = input.ReadString();
            break;
          }
          case 50: {
            GameoverBackgroundImage = input.ReadString();
            break;
          }
          case 56: {
            InitialContinueCount = input.ReadInt32();
            break;
          }
          case 66: {
            CursorImage = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            TitleScreenBackgroundImage = input.ReadString();
            break;
          }
          case 26: {
            TitleScreenLogoImage = input.ReadString();
            break;
          }
          case 34: {
            InitialSceneFile = input.ReadString();
            break;
          }
          case 42: {
            GameoverImage = input.ReadString();
            break;
          }
          case 50: {
            GameoverBackgroundImage = input.ReadString();
            break;
          }
          case 56: {
            InitialContinueCount = input.ReadInt32();
            break;
          }
          case 66: {
            CursorImage = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ModFiles : pb::IMessage<ModFiles>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ModFiles> _parser = new pb::MessageParser<ModFiles>(() => new ModFiles());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ModFiles> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Protobuf.Message.MessagesReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ModFiles() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ModFiles(ModFiles other) : this() {
      files_ = other.files_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ModFiles Clone() {
      return new ModFiles(this);
    }

    /// <summary>Field number for the "files" field.</summary>
    public const int FilesFieldNumber = 1;
    private static readonly pb::FieldCodec<string> _repeated_files_codec
        = pb::FieldCodec.ForString(10);
    private readonly pbc::RepeatedField<string> files_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> Files {
      get { return files_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ModFiles);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ModFiles other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!files_.Equals(other.files_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= files_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      files_.WriteTo(output, _repeated_files_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      files_.WriteTo(ref output, _repeated_files_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += files_.CalculateSize(_repeated_files_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ModFiles other) {
      if (other == null) {
        return;
      }
      files_.Add(other.files_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            files_.AddEntriesFrom(input, _repeated_files_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            files_.AddEntriesFrom(ref input, _repeated_files_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Gonna have to do something different 
  /// TODO: See how is rows and cols calculated
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Map : pb::IMessage<Map>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Map> _parser = new pb::MessageParser<Map>(() => new Map());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Map> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Protobuf.Message.MessagesReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Map() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Map(Map other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Map Clone() {
      return new Map(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Map);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Map other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Map other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class SimpleString : pb::IMessage<SimpleString>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SimpleString> _parser = new pb::MessageParser<SimpleString>(() => new SimpleString());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SimpleString> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Protobuf.Message.MessagesReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SimpleString() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SimpleString(SimpleString other) : this() {
      message_ = other.message_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SimpleString Clone() {
      return new SimpleString(this);
    }

    /// <summary>Field number for the "message" field.</summary>
    public const int MessageFieldNumber = 1;
    private string message_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SimpleString);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SimpleString other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Message != other.Message) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Message.Length != 0) hash ^= Message.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Message.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Message);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Message.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Message);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Message.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SimpleString other) {
      if (other == null) {
        return;
      }
      if (other.Message.Length != 0) {
        Message = other.Message;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Message = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Message = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ActorCombatConfig : pb::IMessage<ActorCombatConfig>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ActorCombatConfig> _parser = new pb::MessageParser<ActorCombatConfig>(() => new ActorCombatConfig());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ActorCombatConfig> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Protobuf.Message.MessagesReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ActorCombatConfig() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ActorCombatConfig(ActorCombatConfig other) : this() {
      attackRange_ = other.attackRange_;
      attackDamage_ = other.attackDamage_;
      criticalHitRate_ = other.criticalHitRate_;
      attackWindup_ = other.attackWindup_;
      attackRecovery_ = other.attackRecovery_;
      attackCooldown_ = other.attackCooldown_;
      stateName_ = other.stateName_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ActorCombatConfig Clone() {
      return new ActorCombatConfig(this);
    }

    /// <summary>Field number for the "attackRange" field.</summary>
    public const int AttackRangeFieldNumber = 1;
    private int attackRange_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int AttackRange {
      get { return attackRange_; }
      set {
        attackRange_ = value;
      }
    }

    /// <summary>Field number for the "attackDamage" field.</summary>
    public const int AttackDamageFieldNumber = 2;
    private int attackDamage_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int AttackDamage {
      get { return attackDamage_; }
      set {
        attackDamage_ = value;
      }
    }

    /// <summary>Field number for the "criticalHitRate" field.</summary>
    public const int CriticalHitRateFieldNumber = 3;
    private float criticalHitRate_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float CriticalHitRate {
      get { return criticalHitRate_; }
      set {
        criticalHitRate_ = value;
      }
    }

    /// <summary>Field number for the "attackWindup" field.</summary>
    public const int AttackWindupFieldNumber = 4;
    private float attackWindup_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float AttackWindup {
      get { return attackWindup_; }
      set {
        attackWindup_ = value;
      }
    }

    /// <summary>Field number for the "attackRecovery" field.</summary>
    public const int AttackRecoveryFieldNumber = 5;
    private float attackRecovery_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float AttackRecovery {
      get { return attackRecovery_; }
      set {
        attackRecovery_ = value;
      }
    }

    /// <summary>Field number for the "attackCooldown" field.</summary>
    public const int AttackCooldownFieldNumber = 6;
    private float attackCooldown_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float AttackCooldown {
      get { return attackCooldown_; }
      set {
        attackCooldown_ = value;
      }
    }

    /// <summary>Field number for the "stateName" field.</summary>
    public const int StateNameFieldNumber = 7;
    private string stateName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string StateName {
      get { return stateName_; }
      set {
        stateName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ActorCombatConfig);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ActorCombatConfig other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (AttackRange != other.AttackRange) return false;
      if (AttackDamage != other.AttackDamage) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(CriticalHitRate, other.CriticalHitRate)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(AttackWindup, other.AttackWindup)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(AttackRecovery, other.AttackRecovery)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(AttackCooldown, other.AttackCooldown)) return false;
      if (StateName != other.StateName) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (AttackRange != 0) hash ^= AttackRange.GetHashCode();
      if (AttackDamage != 0) hash ^= AttackDamage.GetHashCode();
      if (CriticalHitRate != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(CriticalHitRate);
      if (AttackWindup != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(AttackWindup);
      if (AttackRecovery != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(AttackRecovery);
      if (AttackCooldown != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(AttackCooldown);
      if (StateName.Length != 0) hash ^= StateName.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (AttackRange != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(AttackRange);
      }
      if (AttackDamage != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(AttackDamage);
      }
      if (CriticalHitRate != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(CriticalHitRate);
      }
      if (AttackWindup != 0F) {
        output.WriteRawTag(37);
        output.WriteFloat(AttackWindup);
      }
      if (AttackRecovery != 0F) {
        output.WriteRawTag(45);
        output.WriteFloat(AttackRecovery);
      }
      if (AttackCooldown != 0F) {
        output.WriteRawTag(53);
        output.WriteFloat(AttackCooldown);
      }
      if (StateName.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(StateName);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (AttackRange != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(AttackRange);
      }
      if (AttackDamage != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(AttackDamage);
      }
      if (CriticalHitRate != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(CriticalHitRate);
      }
      if (AttackWindup != 0F) {
        output.WriteRawTag(37);
        output.WriteFloat(AttackWindup);
      }
      if (AttackRecovery != 0F) {
        output.WriteRawTag(45);
        output.WriteFloat(AttackRecovery);
      }
      if (AttackCooldown != 0F) {
        output.WriteRawTag(53);
        output.WriteFloat(AttackCooldown);
      }
      if (StateName.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(StateName);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (AttackRange != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(AttackRange);
      }
      if (AttackDamage != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(AttackDamage);
      }
      if (CriticalHitRate != 0F) {
        size += 1 + 4;
      }
      if (AttackWindup != 0F) {
        size += 1 + 4;
      }
      if (AttackRecovery != 0F) {
        size += 1 + 4;
      }
      if (AttackCooldown != 0F) {
        size += 1 + 4;
      }
      if (StateName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(StateName);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ActorCombatConfig other) {
      if (other == null) {
        return;
      }
      if (other.AttackRange != 0) {
        AttackRange = other.AttackRange;
      }
      if (other.AttackDamage != 0) {
        AttackDamage = other.AttackDamage;
      }
      if (other.CriticalHitRate != 0F) {
        CriticalHitRate = other.CriticalHitRate;
      }
      if (other.AttackWindup != 0F) {
        AttackWindup = other.AttackWindup;
      }
      if (other.AttackRecovery != 0F) {
        AttackRecovery = other.AttackRecovery;
      }
      if (other.AttackCooldown != 0F) {
        AttackCooldown = other.AttackCooldown;
      }
      if (other.StateName.Length != 0) {
        StateName = other.StateName;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            AttackRange = input.ReadInt32();
            break;
          }
          case 16: {
            AttackDamage = input.ReadInt32();
            break;
          }
          case 29: {
            CriticalHitRate = input.ReadFloat();
            break;
          }
          case 37: {
            AttackWindup = input.ReadFloat();
            break;
          }
          case 45: {
            AttackRecovery = input.ReadFloat();
            break;
          }
          case 53: {
            AttackCooldown = input.ReadFloat();
            break;
          }
          case 58: {
            StateName = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            AttackRange = input.ReadInt32();
            break;
          }
          case 16: {
            AttackDamage = input.ReadInt32();
            break;
          }
          case 29: {
            CriticalHitRate = input.ReadFloat();
            break;
          }
          case 37: {
            AttackWindup = input.ReadFloat();
            break;
          }
          case 45: {
            AttackRecovery = input.ReadFloat();
            break;
          }
          case 53: {
            AttackCooldown = input.ReadFloat();
            break;
          }
          case 58: {
            StateName = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
